"""Markdown report template skeleton: parse and render into python-docx.

A Markdown template declares the static skeleton of a report (headings, body
texts, tables); dynamic data sections are injected by the report engine at
anchor headings (see minimal_docx / GuangdongChapterWriter). Image references
render as placeholder paragraphs (report images are generated by the engine).
"""
from __future__ import annotations

from copy import deepcopy
import math
import re
import tomllib
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable


@dataclass
class Block:
    kind: str  # heading | paragraph | table | picture
    level: int = 0
    text: str = ""
    rows: list[list[str]] = field(default_factory=list)
    caption: str = ""


DEFAULT_CONFIG: dict[str, Any] = {
    "page": {
        "paper": "A4",
        "orientation": "portrait",
        "left_margin_cm": 2.5,
        "right_margin_cm": 2.5,
        "top_margin_cm": 2.5,
        "bottom_margin_cm": 2.5,
    },
    "body": {
        "east_asia": "仿宋_GB2312",
        "latin": "Times New Roman",
        "size_pt": 10.5,
        "alignment": "justify",
        "first_line_chars": 2,
        "line_spacing": 1.5,
        "space_before_pt": 0,
        "space_after_pt": 0,
    },
    "heading": {
        str(level): {
            "east_asia": "黑体" if level <= 3 else "仿宋_GB2312",
            "latin": "Times New Roman",
            "size_pt": {1: 16, 2: 15, 3: 14, 4: 12, 5: 10.5}[level],
            "bold": False,
            "alignment": "left",
            "space_before_pt": 10 if level == 1 else 6,
            "space_after_pt": 6,
            "keep_with_next": True,
            "page_break_before": False,
            "outline_level": level - 1,
        }
        for level in range(1, 6)
    },
    "table": {
        "east_asia": "仿宋_GB2312",
        "latin": "Times New Roman",
        "size_pt": 10.5,
        "alignment": "center",
        "header_bold": True,
        "header_shading": "1F4E78",
        "allow_row_break": True,
    },
    "caption": {
        "east_asia": "黑体",
        "latin": "Times New Roman",
        "size_pt": 10.5,
        "alignment": "center",
        "space_before_pt": 6,
        "space_after_pt": 4,
    },
    "toc": {
        "enabled": False,
        "title": "目 录",
        "min_level": 1,
        "max_level": 5,
        "update_on_open": True,
    },
}


@dataclass
class Template:
    config: dict[str, Any]
    blocks: list[Block]


_FIELD_KINDS = {
    "page": {
        "paper": "paper",
        "orientation": "orientation",
        "left_margin_cm": "margin",
        "right_margin_cm": "margin",
        "top_margin_cm": "margin",
        "bottom_margin_cm": "margin",
    },
    "body": {
        "east_asia": "text",
        "latin": "text",
        "size_pt": "size",
        "alignment": "alignment",
        "first_line_chars": "int_nonnegative",
        "line_spacing": "positive",
        "space_before_pt": "nonnegative",
        "space_after_pt": "nonnegative",
    },
    "table": {
        "east_asia": "text",
        "latin": "text",
        "size_pt": "size",
        "alignment": "alignment",
        "header_bold": "bool",
        "header_shading": "text",
        "allow_row_break": "bool",
    },
    "caption": {
        "east_asia": "text",
        "latin": "text",
        "size_pt": "size",
        "alignment": "alignment",
        "bold": "bool",
        "space_before_pt": "nonnegative",
        "space_after_pt": "nonnegative",
    },
    "toc": {
        "enabled": "bool",
        "title": "text",
        "min_level": "level",
        "max_level": "level",
        "update_on_open": "bool",
        "east_asia": "text",
    },
}

_HEADING_FIELD_KINDS = {
    "east_asia": "text",
    "latin": "text",
    "size_pt": "size",
    "bold": "bool",
    "alignment": "alignment",
    "space_before_pt": "nonnegative",
    "space_after_pt": "nonnegative",
    "line_spacing": "positive",
    "keep_with_next": "bool",
    "page_break_before": "bool",
    "outline_level": "int_nonnegative",
}


def _invalid_config(path: Path, field_name: str, reason: str) -> ValueError:
    return ValueError(f"模板 {path} 配置字段 {field_name} 无效：{reason}")


def _validate_value(path: Path, field_name: str, value: Any, kind: str) -> None:
    if kind == "text":
        if not isinstance(value, str) or not value.strip():
            raise _invalid_config(path, field_name, "必须为非空字符串")
        return
    if kind == "paper":
        if not isinstance(value, str) or value != "A4":
            raise _invalid_config(path, field_name, "只允许 A4")
        return
    if kind == "orientation":
        if not isinstance(value, str) or value not in {"portrait", "landscape"}:
            raise _invalid_config(path, field_name, "只允许 portrait 或 landscape")
        return
    if kind == "alignment":
        if not isinstance(value, str) or value not in {"left", "center", "right", "justify"}:
            raise _invalid_config(path, field_name, "只允许 left、center、right、justify")
        return
    if kind == "bool":
        if not isinstance(value, bool):
            raise _invalid_config(path, field_name, "必须为布尔值")
        return
    if kind == "int_nonnegative":
        if isinstance(value, bool) or not isinstance(value, int) or value < 0:
            raise _invalid_config(path, field_name, "必须为非负整数")
        return
    if kind == "level":
        if isinstance(value, bool) or not isinstance(value, int) or not 1 <= value <= 5:
            raise _invalid_config(path, field_name, "必须为 1~5 的整数")
        return
    if kind in {"margin", "size", "positive", "nonnegative"}:
        if isinstance(value, bool) or not isinstance(value, (int, float)):
            raise _invalid_config(path, field_name, "必须为数值")
        if isinstance(value, float) and not math.isfinite(value):
            raise _invalid_config(path, field_name, "必须为有限数值")
        if kind == "margin" and not 0 <= value <= 10:
            raise _invalid_config(path, field_name, "必须在 0~10 cm 范围内")
        if kind == "size" and not 0 < value <= 72:
            raise _invalid_config(path, field_name, "必须大于 0 且不大于 72 磅")
        if kind == "positive" and value <= 0:
            raise _invalid_config(path, field_name, "必须为正数")
        if kind == "nonnegative" and value < 0:
            raise _invalid_config(path, field_name, "必须为非负数")
        return
    raise RuntimeError(f"unknown config field kind: {kind}")


def _validate_config(path: Path, raw_config: dict[str, Any]) -> None:
    known_sections = set(_FIELD_KINDS) | {"heading"}
    for section, values in raw_config.items():
        if section not in known_sections:
            raise _invalid_config(path, section, "不支持的配置项")
        if not isinstance(values, dict):
            raise _invalid_config(path, section, "必须为 TOML 表")
        if section == "heading":
            for level, heading_config in values.items():
                field_name = f"heading.{level}"
                if level not in DEFAULT_CONFIG["heading"]:
                    raise _invalid_config(path, field_name, "标题级别只允许 1~5")
                if not isinstance(heading_config, dict):
                    raise _invalid_config(path, field_name, "必须为 TOML 表")
                for key, value in heading_config.items():
                    if key not in _HEADING_FIELD_KINDS:
                        raise _invalid_config(path, f"{field_name}.{key}", "不支持的配置项")
                    _validate_value(path, f"{field_name}.{key}", value, _HEADING_FIELD_KINDS[key])
            continue
        for key, value in values.items():
            if key not in _FIELD_KINDS[section]:
                raise _invalid_config(path, f"{section}.{key}", "不支持的配置项")
            _validate_value(path, f"{section}.{key}", value, _FIELD_KINDS[section][key])

    toc = raw_config.get("toc", {})
    if isinstance(toc, dict) and "min_level" in toc and "max_level" in toc:
        if toc["min_level"] > toc["max_level"]:
            raise _invalid_config(path, "toc.min_level", "不能大于 toc.max_level")


def _deep_merge(base: dict[str, Any], override: dict[str, Any]) -> None:
    for key, value in override.items():
        if isinstance(value, dict) and isinstance(base.get(key), dict):
            _deep_merge(base[key], value)
        else:
            base[key] = value


def _split_front_matter(text: str, path: Path) -> tuple[dict[str, Any], str]:
    lines = text.splitlines()
    if not lines or lines[0].strip() != "+++":
        return {}, text
    last_error = None
    found_separator = False
    for end in range(1, len(lines)):
        if lines[end].strip() != "+++":
            continue
        found_separator = True
        front_matter = "\n".join(lines[1:end])
        try:
            config = tomllib.loads(front_matter)
        except tomllib.TOMLDecodeError as exc:
            # 合法 TOML 多行字符串可以包含独立的 +++ 行；继续寻找真正的结束标记。
            last_error = exc
            continue
        if not isinstance(config, dict):
            raise ValueError(f"模板 {path} 的 TOML 配置必须为表")
        return config, "\n".join(lines[end + 1 :])
    if found_separator and last_error is not None:
        raise ValueError(f"模板 {path} 的 TOML 配置无效：{last_error}") from last_error
    raise ValueError(f"模板 {path} 的 TOML 配置未闭合")


def parse_blocks(text: str) -> list[Block]:
    """Parse Markdown text into skeleton blocks (small supported subset)."""
    blocks: list[Block] = []
    lines = text.splitlines()
    index = 0
    while index < len(lines):
        line = lines[index]
        stripped = line.strip()
        if not stripped:
            index += 1
            continue
        if stripped == "<!-- toc -->":
            blocks.append(Block("toc"))
            index += 1
            continue
        cover = re.match(r"^#\s*@cover\s+(.*)$", stripped)
        if cover:
            blocks.append(Block("cover", text=cover.group(1).strip()))
            index += 1
            continue
        notes = re.match(r"^#\s*@notes\s+(.*)$", stripped)
        if notes:
            blocks.append(Block("notes", text=notes.group(1).strip()))
            index += 1
            continue
        if stripped.startswith("```"):
            # fenced code block: keep as single paragraph text
            content = []
            index += 1
            while index < len(lines) and not lines[index].strip().startswith("```"):
                content.append(lines[index])
                index += 1
            index += 1
            blocks.append(Block("paragraph", text="\n".join(content)))
            continue
        if stripped.startswith("|") and "|" in stripped[1:]:
            rows = []
            while index < len(lines) and lines[index].strip().startswith("|"):
                row = [cell.strip() for cell in lines[index].strip().strip("|").split("|")]
                if not all(re.fullmatch(r":?-{3,}:?", cell) for cell in row):
                    rows.append(row)
                index += 1
            if rows:
                blocks.append(Block("table", rows=rows))
            continue
        heading = re.match(r"^(#{1,6})\s+(.*)$", stripped)
        if heading:
            blocks.append(Block("heading", level=len(heading.group(1)), text=heading.group(2).strip()))
            index += 1
            continue
        picture = re.match(r"^!\[[^\]]*\]\(([^)]+)\)$", stripped)
        if picture:
            blocks.append(Block("picture", caption=picture.group(1)))
            index += 1
            continue
        # plain paragraph; merge consecutive plain lines
        paragraph_lines = [line]
        index += 1
        while index < len(lines):
            next_line = lines[index]
            next_stripped = next_line.strip()
            if not next_stripped or next_stripped.startswith(("#", "|", "!", "```")):
                break
            paragraph_lines.append(next_line)
            index += 1
        blocks.append(Block("paragraph", text="\n".join(paragraph_lines).strip()))
    return blocks


def parse(text: str) -> list[Block]:
    return parse_blocks(text)


def read_template(path: Path) -> Template:
    path = Path(path)
    raw_text = path.read_text(encoding="utf-8")
    raw_config, body = _split_front_matter(raw_text, path)
    _validate_config(path, raw_config)
    config = deepcopy(DEFAULT_CONFIG)
    _deep_merge(config, raw_config)
    if config["toc"]["min_level"] > config["toc"]["max_level"]:
        raise _invalid_config(path, "toc.min_level", "不能大于 toc.max_level")
    blocks = parse_blocks(body)
    if config["toc"]["enabled"] and not any(block.kind == "toc" for block in blocks):
        raise ValueError(f"模板 {path} 配置字段 toc.enabled 无效：正文必须包含 <!-- toc -->")
    return Template(config=config, blocks=blocks)


def read_blocks(path: Path) -> list[Block]:
    return read_template(path).blocks


def render_skeleton(
    doc,
    blocks: list[Block],
    *,
    heading: Callable[[str, int], object],
    body: Callable[[str], object] | None = None,
    table: Callable[[list[str], list[list[str]], bool], object] | None = None,
    picture: Callable[[str], object] | None = None,
    toc: Callable[[], object] | None = None,
    cover: Callable[[str], object] | None = None,
    skip_headings: Callable[[str, int], bool] | None = None,
    replace: dict[str, str] | None = None,
) -> None:
    """Render skeleton blocks into *doc* using the provided style callbacks."""
    for block in blocks:
        text = block.text
        if replace and text:
            for placeholder, value in replace.items():
                text = text.replace(placeholder, value)
        if block.kind == "toc":
            if toc is not None:
                toc()
        elif block.kind == "cover":
            if cover is not None:
                cover(text)
        elif block.kind == "notes":
            if notes is not None:
                notes(text)
        elif block.kind == "heading":
            if skip_headings and skip_headings(text, block.level):
                continue
            heading(text, block.level)
        elif block.kind == "paragraph":
            if body is not None and text:
                body(text)
        elif block.kind == "table":
            if table is not None and block.rows:
                table(block.rows[0], block.rows[1:], False)
        elif block.kind == "picture":
            if picture is not None:
                picture(block.caption)
