"""Markdown report template skeleton: parse and render into python-docx.

A Markdown template declares the static skeleton of a report (headings, body
texts, tables); dynamic data sections are injected by the report engine at
anchor headings (see minimal_docx / GuangdongChapterWriter). Image references
render as placeholder paragraphs (report images are generated by the engine).
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable


@dataclass
class Block:
    kind: str  # heading | paragraph | table | picture
    level: int = 0
    text: str = ""
    rows: list[list[str]] = field(default_factory=list)
    caption: str = ""


def parse(text: str) -> list[Block]:
    """Parse Markdown text into skeleton blocks (small supported subset)."""
    blocks: list[Block] = []
    lines = text.splitlines()
    index = 0
    while index < len(lines):
        line = lines[index]
        stripped = line.strip()
        if not stripped:
            index += 1
            continue
        if stripped.startswith("```"):
            # fenced code block: keep as single paragraph text
            content = []
            index += 1
            while index < len(lines) and not lines[index].strip().startswith("```"):
                content.append(lines[index])
                index += 1
            index += 1
            blocks.append(Block("paragraph", text="\n".join(content)))
            continue
        if stripped.startswith("|") and "|" in stripped[1:]:
            rows = []
            while index < len(lines) and lines[index].strip().startswith("|"):
                row = [cell.strip() for cell in lines[index].strip().strip("|").split("|")]
                if not all(re.fullmatch(r":?-{3,}:?", cell) for cell in row):
                    rows.append(row)
                index += 1
            if rows:
                blocks.append(Block("table", rows=rows))
            continue
        heading = re.match(r"^(#{1,6})\s+(.*)$", stripped)
        if heading:
            blocks.append(Block("heading", level=len(heading.group(1)), text=heading.group(2).strip()))
            index += 1
            continue
        picture = re.match(r"^!\[[^\]]*\]\(([^)]+)\)$", stripped)
        if picture:
            blocks.append(Block("picture", caption=picture.group(1)))
            index += 1
            continue
        # plain paragraph; merge consecutive plain lines
        paragraph_lines = [line]
        index += 1
        while index < len(lines):
            next_line = lines[index]
            next_stripped = next_line.strip()
            if not next_stripped or next_stripped.startswith(("#", "|", "!", "```")):
                break
            paragraph_lines.append(next_line)
            index += 1
        blocks.append(Block("paragraph", text="\n".join(paragraph_lines).strip()))
    return blocks


def read_blocks(path: Path) -> list[Block]:
    return parse(path.read_text(encoding="utf-8"))


def render_skeleton(
    doc,
    blocks: list[Block],
    *,
    heading: Callable[[str, int], object],
    body: Callable[[str], object] | None = None,
    table: Callable[[list[str], list[list[str]], bool], object] | None = None,
    picture: Callable[[str], object] | None = None,
    skip_headings: Callable[[str, int], bool] | None = None,
    replace: dict[str, str] | None = None,
) -> None:
    """Render skeleton blocks into *doc* using the provided style callbacks."""
    for block in blocks:
        text = block.text
        if replace and text:
            for placeholder, value in replace.items():
                text = text.replace(placeholder, value)
        if block.kind == "heading":
            if skip_headings and skip_headings(text, block.level):
                continue
            heading(text, block.level)
        elif block.kind == "paragraph":
            if body is not None and text:
                body(text)
        elif block.kind == "table":
            if table is not None and block.rows:
                table(block.rows[0], block.rows[1:], False)
        elif block.kind == "picture":
            if picture is not None:
                picture(block.caption)
